name: docs-linkcheck
permissions:
  contents: read

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check documentation links
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --no-progress --exclude-mail --timeout 10s docs/**/*.md
