data_dir: "$HOME/.local/state/hauski"
models_dir: "./models"

server:
  host: 127.0.0.1
  port: 8080

obsidian:
  vault_path: "$HOME/vault-gewebe"

index:
  path: "$HOME/.local/state/hauski/index"
  provider:
    embedder: "ollama"
    model: "nomic-embed-text"
    url: "http://127.0.0.1:11434"

budgets:
  index_topk20_ms: 60

plugins:
  enabled:
    - "obsidian_index"
