name: reusable-ci
on:
  workflow_call:
    inputs:
      run_lint:
        required: false
        type: boolean
        default: true
      run_tests:
        required: false
        type: boolean
        default: false

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Show WGX profile if present
        run: |
          test -f .wgx/profile.yml && echo "Found .wgx/profile.yml" || echo "No .wgx/profile.yml"

      - name: Lint (optional)
        if: ${{ inputs.run_lint }}
        run: |
          just lint || echo "No lint target – skipping"

      - name: Tests (optional)
        if: ${{ inputs.run_tests }}
        run: |
          just test || echo "No tests – skipping"
