name: wgx-smoke
on:
  workflow_dispatch:
  push:
    paths:
      - ".wgx/**"
      - "docs/wgx-konzept.md"

jobs:
  smoke:
    uses: heimgewebe/metarepo/.github/workflows/reusable-ci.yml@main
    with:
      run_lint: true
      run_tests: false
