[package]
name = "hauski-indexd"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
