# Retries & Timeouts
max_redirects = 5
timeout = 10
retry_wait_time = 2
retry_count = 2

# Private/temporäre Hosts ignorieren (Beispiele)
exclude = [
  "localhost",
  "127.0.0.1",
  "0.0.0.0"
]

# Pfade: node_modules & Git-Ordner ausnehmen
exclude_path = [
  "node_modules",
  ".git"
]
