name: CI
on:
  push:
  pull_request:
jobs:
  rust:
    runs-on: ubuntu-24.04
    env:
      toolchain: stable
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-deny and just
        run: cargo install cargo-deny just
      - name: fmt
        run: cargo fmt --all --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: cargo-deny
        run: cargo deny check
      - name: test
        run: cargo test --workspace -- --nocapture