name: wgx-check
description: "Prüft ein Ziel-Repo gegen angegebene wgx-Version"
inputs:
  repo:
    description: "Repository, das getestet werden soll"
    required: true
  ref:
    description: "Ref im Ziel-Repo"
    required: false
    default: "main"
  wgx_ref:
    description: "Ref des wgx-Repos"
    required: false
    default: "main"
runs:
  using: "composite"
  steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}

    - name: Checkout wgx (self)
      uses: actions/checkout@v4
      with:
        path: wgx
        ref: ${{ inputs.wgx_ref }}

    - name: Install basics
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y bash coreutils git curl jq
        sudo apt-get install -y build-essential pkg-config || true
        curl https://sh.rustup.rs -sSf | sh -s -- -y >/dev/null 2>&1 || true
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        if command -v pnpm >/dev/null 2>&1; then
          echo "pnpm already available"
        else
          curl -fsSL https://get.pnpm.io/install.sh | sh -s -- --silent || true
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
        fi

    - name: Link wgx
      shell: bash
      run: |
        chmod +x wgx/wgx
        echo "${PWD}/wgx" >> $GITHUB_PATH

    - name: Sanity
      shell: bash
      run: |
        ./wgx/wgx version || true
        if ! ls .wgx/profile.* >/dev/null 2>&1; then
          echo "profile manifest fehlt"
          exit 1
        fi

    - name: Validate manifest
      shell: bash
      run: |
        wgx validate --json | jq -e '.ok==true'

    - name: Execute safe tasks
      shell: bash
      run: |
        set -euo pipefail
        tasks_json="$(wgx tasks --json --groups)"
        if echo "$tasks_json" | jq -e '.tasks[] | select(.name=="doctor" and .safe==true)' >/dev/null; then
          wgx task doctor || true
        fi
        if echo "$tasks_json" | jq -e '.tasks[] | select(.name=="test" and .safe==true)' >/dev/null; then
          wgx task test
        fi

