name: ci
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust:
    name: Rust – fmt, clippy, tests, deny
    runs-on: ubuntu-latest
    defaults: { run: { shell: bash } }
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: cargo test
        run: cargo test --all --quiet

      - name: cargo deny
        uses: EmbarkStudios/cargo-deny-action@v1

  repo:
    name: Repo – markdown & shell lint (soft)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdownlint
        run: |
          npm i -g markdownlint-cli@0.41.0
          git ls-files '*.md' | xargs -r markdownlint
      - name: ShellCheck
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          git ls-files '*.sh' | xargs -r shellcheck -x
